### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by ramandatascientist** [spectacles-ci/lkmlstyle#4]
Hello,

When we trying to run the linter locally using command line, we see these errors. Not sure if there are specific to any Python version or missing library?

![image](https://user-images.githubusercontent.com/50452830/161600247-2a5bbad2-67b5-4cc8-a3dd-37761a24540e.png)

**Comment by joshtemple** [comment]
Thanks Raman! Can you provide a snippet of LookML that reproduces this error? That will be the fastest way to help me debug.

**Comment by ramandatascientist** [comment]
Sure, Below is the LookML (.view file) that we were testing to scan


i```
nclude: "pdt_episode_scorecard.view"
include: "_period_comparison.view"
include: "cte_outreach_sort_sequence.view"

view: outreach {
  extends: [_period_comparison]
  sql_table_name: gold.dashboards.outreach ;;


# this object is created to support our second Explorer (Channel Engagement). It is not possible to add this to our first Explorer ('Episode Trip') because some measures does not go along with others (eg:Payment made by channel)
  dimension: primary_key {
    # helper field, used for symmetric aggregiations
    type: number
    primary_key: yes
    hidden: yes
    sql: row_number() over (order by ${refreshed_timestamp_date} desc);;
  }



  dimension: activity_type {
    # helper field, used for filtering measures
    description: "Type of activity (i.e. Click, SMS, etc.)"
    hidden: yes
    type: string
    sql: ${TABLE}."ACTIVITY_TYPE" ;;
  }

  dimension: channel {
    description: "Outreach channel used. (i.e. Email, SMS, etc.)"
    type: string
    sql: ${TABLE}."CHANNEL" ;;
  }

  dimension: client_key {
    label: "Organization Name"
    description: "The name of the organization that allocates customers for treatment."
    type: string
    sql: case
          when ${TABLE}.client_key = 'rogers' then 'Rogers'
          when ${TABLE}.client_key = 'fido' then 'Fido'
          when ${TABLE}.client_key = 'telus' then 'TELUS Wireless'
          when ${TABLE}.client_key = 'telus-wln' then 'TELUS Wireline'
          when ${TABLE}.client_key = 'koodo-mobile' then 'Koodo'
          when ${TABLE}.client_key = 'tmobile' then 'T-Mobile'
          when ${TABLE}.client_key = 'cww' then 'Carolina West Wireless'
          when ${TABLE}.client_key = 'uscell' then 'US Cell'
          when ${TABLE}.client_key = 'uscell2' then 'US Cell 2'
          when ${TABLE}.client_key = 'shaw-business' then 'Shaw Business Legacy'
          when ${TABLE}.client_key = 'highdeal' then 'Shaw Highdeal'
          when ${TABLE}.client_key = 'verizon' then 'Verizon'
          when ${TABLE}.client_key = 'shawbiz' then 'Shaw Business'
          when ${TABLE}.client_key = 'bell' then 'Bell'
          when ${TABLE}.client_key = 'virgin-plus' then 'Virgin Plus'
          else ${TABLE}.client_key
          end;;
  }

  dimension: raw_client_key {
    # helper field, used for access_filter & user_attributes
    type: string
    hidden: yes
    sql: ${TABLE}.client_key ;;
  }

  dimension: episode_key {
    # field is hashed to hide episode keys since it also contains account number
    # you can always lookup the actual episode_key from hash key eg: select episode_key from dashboards.episode where md5(episode_key) = '11c071267a4a55227b9a4c02ac96dfbc'
    label: "Episode Key"
    description: "This represents the unique ID of an episode."
    type: string
    sql: md5(${TABLE}."EPISODE_KEY") ;;
  }

  dimension: memo {
    label: "Outreach Memo"
    description: "The descriptive title of a specific outreach."
    type: string
    sql: trim(replace(replace(${TABLE}."MEMO", '–', '-'), '_', '-'));;
    order_by_field:cte_outreach_sort_sequence.outreach_sort_sequence

  }

  dimension_group: event_start {
    # helper field, used for drilling
    label: "Outreach Sent"
    description: "The date when the outreach occurred on."
    type: time
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}."OUTREACH_EVENT_TIMESTAMP_UTC" ;;
  }

#This is needed for Period over Period analysis
  dimension_group: pop_event {
    hidden: yes
    type: time
    timeframes: [
      raw, time, date, week, month, month_name, quarter, year
    ]
    convert_tz: no
    datatype: date
    sql:-- spectacles: ignore
      ${pdt_episode_scorecard.episode_start_date};;

  }


  dimension: subject_behavior_tactic_name {
    label: "Behaviour Tactic - Subject"
    description: "Behavioral science tactic employed."
    type: string
    sql: ${TABLE}."SUBJECT_BEHAVIOR_TACTIC_NAME" ;;
  }

  dimension: body_behavior_tactic_name {
    label: "Behaviour Tactic - Body"
    description: "Behavioral science tactic employed."
    type: string
    sql: ${TABLE}."BODY_BEHAVIOR_TACTIC_NAME" ;;
  }

  dimension_group: refreshed_timestamp {
    # helper field, used for composite primary key
    hidden: yes
    type: time
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}."REFRESHED_TIMESTAMP" ;;
  }



  dimension: release_key {
    # helper field, used for filtering measures
    hidden: yes
    type: string
    sql: ${TABLE}."RELEASE_KEY" ;;
  }

  dimension: treatment_path_name {
    label: "Treatment Path Name"
    description: "The treatment approach that is used to treat a group of like customers."
    type: string
    sql: ${TABLE}."TREATMENT_PATH_NAME" ;;
  }

  dimension: treatment_path_type {
    label: "Treatment Type"
    description: "A drip treatment is the regular cadence of outreaches that a delinquent customer. A nurture is an addition to that path, usually created by the the adoption of a special offer (e.g. a payment reminder)."
    type: string
    sql: ${TABLE}."TREATMENT_PATH_TYPE" ;;
  }

  dimension: days_in_treatment {
    description: "The number of days that has past since episode date. Use for data normalization."
    type: number
    sql: datediff(day,${pdt_episode_scorecard.episode_start_date},${event_start_date});;
  }

  # Email Measures

  measure: unique_email_sent_episode_count {
    label: "Email - Sent (Count)"
    description: "Number of emails that were sent to the customers."
    group_label: "Email"
    type: count_distinct
    value_format_name: millions_formatting
    sql: concat(${episode_key},${client_key},${release_key});;
    filters: [activity_type: "Sent", channel: "Email"]
    drill_fields: [detail*]
  }

  measure: unique_email_delivered_episode_count {
    label: "Email - Delivered (Count)"
    description: "Number of sent emails that were recieved by the customer."
    group_label: "Email"
    type: count_distinct
    value_format_name: millions_formatting
    sql: concat(${episode_key},${client_key},${release_key});;
    filters: [activity_type: "Delivered", channel: "Email"]
    drill_fields: [detail*]
  }

  measure: email_delivered_over_sent {
    label: "Email - Delivered (%)"
    description: "The % of sent emails that were actually delivered (recieved). "
    group_label: "Email"
    type: number
    value_format_name: percent_1
    sql: (1.0 * ${unique_email_delivered_episode_count})/nullif(${unique_email_sent_episode_count},0) ;;
    drill_fields: [detail*]
  }

  measure: unique_email_opened_episode_count {
    label: "Email - Opened (Count)"
    description: "Number of delivered emails that were opened by the customers."
    group_label: "Email"
    type: count_distinct
    value_format_name: millions_formatting
    sql: concat(${episode_key},${client_key},${release_key});;
    filters: [activity_type: "Open", channel: "Email"]
    drill_fields: [detail*]
  }

  measure: email_opened_over_delivered {
    label: "Email - Opened (%)"
    description: "The % of delivered emails that were opened."
    group_label: "Email"
    type: number
    value_format_name: percent_1
    sql: (1.0 * ${unique_email_opened_episode_count})/nullif(${unique_email_delivered_episode_count},0) ;;
    drill_fields: [detail*]
  }

  measure: unique_email_clicked_episode_count {
    label: "Email - Clicked (Count)"
    description: "The number of opened emails that have been clicked on by the customer."
    group_label: "Email"
    type: count_distinct
    value_format_name: millions_formatting
    sql: concat(${episode_key},${client_key},${release_key});;
    filters: [activity_type: "Click", channel: "Email"]
    drill_fields: [detail*]
  }

  measure: email_clicked_over_opened {
    label: "Email - Clicked (%)"
    description: "The % of all emails opened that have been clicked."
    group_label: "Email"
    type: number
    value_format_name: percent_1
    sql: (1.0 * ${unique_email_clicked_episode_count})/nullif(${unique_email_opened_episode_count},0) ;;
    drill_fields: [detail*]
  }

# SMS Measures

  measure: unique_sms_sent_episode_count {
    label: "SMS - Sent (Count)"
    description: "Number of SMS that are being sent to the customers."
    group_label: "SMS"
    type: count_distinct
    value_format_name: millions_formatting
    sql: concat(${episode_key},${client_key},${release_key});;
    filters: [activity_type: "Sent", channel: "SMS"]
    drill_fields: [detail*]
  }

  measure: unique_sms_delivered_episode_count {
    label: "SMS - Delivered (Count)"
    description: "Number of sent SMS that were delivered (recieved) by the customers."
    group_label: "SMS"
    type: count_distinct
    value_format_name: millions_formatting
    sql: concat(${episode_key},${client_key},${release_key});;
    filters: [activity_type: "Delivered", channel: "SMS"]
    drill_fields: [detail*]
  }

  measure: sms_delivered_over_sent {
    label: "SMS - Delivered (%)"
    description: "The % of sent SMS that were delivered (recieved) by the customers."
    group_label: "SMS"
    type: number
    value_format_name: percent_1
    sql: (1.0 * ${unique_sms_delivered_episode_count})/nullif(${unique_sms_sent_episode_count},0) ;;
    drill_fields: [detail*]
  }

  measure: unique_sms_clicked_episode_count {
    label: "SMS - Clicked (Count)"
    description: "Number of delivered SMS that are clicked on."
    group_label: "SMS"
    type: count_distinct
    value_format_name: millions_formatting
    sql: concat(${episode_key},${client_key},${release_key});;
    filters: [activity_type: "Click", channel: "SMS"]
    drill_fields: [detail*]
  }

  measure: sms_clicked_over_delivered {
    label: "SMS - Clicked (%)"
    description: "The % of delivered SMS that are clicked on."
    group_label: "SMS"
    type: number
    value_format_name: percent_1
    sql: (1.0 * ${unique_sms_clicked_episode_count})/nullif(${unique_sms_delivered_episode_count},0) ;;
    drill_fields: [detail*]
  }


  set: detail {
    fields: [
      episode_key,
      client_key,
      pdt_episode_scorecard.episode_start_date,
      event_start_date,
      days_in_treatment,
      channel,
      activity_type,
      treatment_path_name,
      treatment_path_type,
      subject_behavior_tactic_name,
      body_behavior_tactic_name,
      memo,
      pdt_episode_scorecard.account_type
    ]

  }
}
```

**Comment by joshtemple** [comment]
Hey Raman! When I copy the above into a file `test.view.lkml` and run lkmlstyle `lkmlstyle test.view.lkml`, it runs successfully. Can you try updating to the latest version of lkmlstyle and running again?

There are also some changes that make it easier to see files that don't have correct syntax, so you should also retry running lkmlstyle over your whole project to confirm the error wasn't in a different file.

**Comment by ramandatascientist** [comment]
Hi @joshtemple I updated my python version to 3.10 and it works as expected. Thank you for looking into this
