### ISSUE TITLE
New Linter rule set request- PDT_ prefix

### ISSUE THREAD

**Issue by ramandatascientist** [spectacles-ci/lkmlstyle#7]
Hello Spectacles,

We would like to see if you can add a new linter rule that will ensure that any pdt view have pdt_ as prefix in their name. This will help us easily identify what views are directly mapped to database and what views are custom queries

**Comment by joshtemple** [comment]
This is live in v0.0.6. Note that you will likely need to upgrade your Python version to 3.10 to install.

```
pip install lkmlstyle==0.0.6
```

Closed by 0b3c955e8f1b94cc4998ea747da5d3d64a347de4.

**Comment by joshtemple** [comment]
Double-check that you're on Python 3.10 and update pip to the latest version as well.

**Comment by Moe633** [comment]
Hey Spectacles,

I still don't see this rule implemented. Was wondering if it was made or is it is still in progress.

**Comment by joshtemple** [comment]
Double-check you're on the right version of `lkmlstyle` by running `pip show lkmlstyle`. It should be at least 0.0.6. If not, try running `pip install -U lkmlstyle` which will update to the latest version.

**Comment by ramandatascientist** [comment]
@joshtemple just validated in Python 3.10 and its working as expected. Thank you for your help on this
